id: P005373
initial_creation_type: ocr
source_metadata:
  id: bdr:W23762
  title: དྲི་མེད་ཤེལ་གོང་དང་དྲི་མེད་ཤེལ་ཕྲེང་དང་ལག་ལེན་གཅེས་བསྡུས
  author: ''
  volumes:
    0bca82adaacd473abf3c6f739ae4493f:
      image_group_id: I2636
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
