id: IA737297C
legacy_id: P005373
ocr_import_info:
  bdrc_scan_id: W23762
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T16:19:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:43:17.755278+00:00'
last_modified: 2022-09-02 12:43:46.690561
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23762
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23762
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲི་མེད་ཤེལ་གོང་དང་དྲི་མེད་ཤེལ་ཕྲེང་དང་ལག་ལེན་གཅེས་བསྡུས།
  author: དེའུ་དམར་དགེ་བཤེས་བསྟན་འཛིན་ཕུན་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.6521740979808053
  ocr_word_median_confidence_index: 0.6899999976158142
quality: null
bases:
  I2636:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2636
      total_pages: 604
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2636.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6521740979808053
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
