id: IA737297C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:22:56+00:00'
last_modified: '2022-06-08T02:37:35.035921+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23762
  title: དྲི་མེད་ཤེལ་གོང་དང་དྲི་མེད་ཤེལ་ཕྲེང་དང་ལག་ལེན་གཅེས་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D9FB:
      image_group_id: I2636
      title: ''
      total_pages: 604
      order: 1
      base_file: D9FB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
